paths:
  /docs/dist/{filename}: {}
  /docs/{path}: {}
  /api/users:
    get:
      summary: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0435 \u0432\u0441\
        \u0435\u0445 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\
        \u0435\u0439"
      responses:
        '200':
          description: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0435 \u0441\
            \u043F\u0438\u0441\u043A\u0430 \u0432\u0441\u0435\u0445 \u043F\u043E\u043B\
            \u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u0435\u0439"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserOutput'
      tags:
      - Users
  /api/users/delete:
    get:
      summary: "\u0412\u043E\u0437\u0432\u043E\u0434\u0438\u0442 \u0447\u0438\u0441\
        \u043B\u043E \u0432 \u0441\u0442\u0435\u043F\u0435\u043D\u044C"
      parameters:
      - in: query
        name: id
        description: id
        schema:
          type: integer
          example: 1
        required: true
      responses:
        '200':
          description: "\u041F\u043E\u043B\u044C\u0445\u043B\u0432\u0430\u044C\u0435\
            \u0434\u0431 \u0443\u0434\u0430\u043B\u0435\u043D"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserOutput'
        '400':
          description: "\u041D\u0435 \u043F\u0435\u0440\u0435\u0434\u0430\u043D \u043E\
            \u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\u044B\u0439 \u043F\
            \u0430\u0440\u0430\u043C\u0435\u0442\u0440"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserError'
      tags:
      - Users
  /swagger: {}
info:
  title: My App
  version: 1.0.0
tags:
- name: math
  description: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u0447\u0435\u0441\
    \u043A\u0438\u0435 \u0444\u0443\u043D\u043A\u0446\u0438\u0438"
openapi: 3.0.3
components:
  schemas:
    Input:
      type: object
      properties:
        power:
          type: integer
          description: "\u0421\u0442\u0435\u043F\u0435\u043D\u044C"
          example: 2
        number:
          type: integer
          description: "\u0427\u0438\u0441\u043B\u043E"
          example: 5
      required:
      - number
      - power
    Output:
      type: object
      properties:
        result:
          type: integer
          description: "\u0420\u0435\u0437\u0443\u043B\u044C\u0442\u0430\u0442"
          example: 25
      required:
      - result
    Error:
      type: object
      properties:
        error:
          type: string
          description: "\u0421\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u0435 \u043E\
            \u0431 \u043E\u0448\u0438\u0431\u043A\u0435"
          example: Invalid input parameter number
      required:
      - error
    UserOutput:
      type: object
      properties:
        result:
          type: integer
          description: "\u0420\u0435\u0437\u0443\u043B\u044C\u0442\u0430\u0442"
          example: 25
      required:
      - result
    UserError:
      type: object
      properties:
        error:
          type: string
          description: "\u0421\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u0435 \u043E\
            \u0431 \u043E\u0448\u0438\u0431\u043A\u0435"
          example: Invalid input parameter number
      required:
      - error
